// <auto-generated />
using System;
using Heloilo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Heloilo.Backend.Migrations
{
    [DbContext(typeof(HeloiloDbContext))]
    [Migration("20251108022423_AddReminderAndAccountDeletionFields")]
    partial class AddReminderAndAccountDeletionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Sent");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("RelationshipId", "SentAt");

                    b.HasIndex("SenderId", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.DailyActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RecurrenceParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecurrenceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("ReminderMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("RecurrenceParentId");

                    b.HasIndex("RecurrenceType");

                    b.HasIndex("UserId", "ActivityDate");

                    b.HasIndex("UserId", "IsCompleted");

                    b.ToTable("DailyActivities");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.EmailVerificationToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Token", "IsUsed", "ExpiresAt");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Favorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ContentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("content_id");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("UserId");

                    b.HasIndex("ContentType", "ContentId");

                    b.HasIndex("UserId", "ContentType", "ContentId")
                        .IsUnique();

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.InitialSetup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("UserId");

                    b.HasIndex("RelationshipId", "UserId")
                        .IsUnique();

                    b.ToTable("InitialSetups");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Memory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MemoryDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("RelationshipId", "MemoryDate");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MemoryMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("MemoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.ToTable("MemoryMedia");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MemoryTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MemoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId", "TagName")
                        .IsUnique();

                    b.ToTable("MemoryTags");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MessageMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileBlob")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.ToTable("MessageMedia");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MoodLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("MoodTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MoodTypeId");

                    b.HasIndex("RelationshipId", "LogDate");

                    b.HasIndex("UserId", "LogDate");

                    b.ToTable("MoodLogs");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MoodType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("MoodCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("MoodCategory", "IsActive");

                    b.ToTable("MoodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(5930),
                            Description = "Sensação de leveza ou satisfação",
                            Emoji = "😊",
                            IsActive = true,
                            MoodCategory = "Positive",
                            Name = "Feliz / Contente",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(5933)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7586),
                            Description = "Energia para fazer coisas",
                            Emoji = "🚀",
                            IsActive = true,
                            MoodCategory = "Positive",
                            Name = "Animado / Motivado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7588)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7591),
                            Description = "Paz interior, sem estresse",
                            Emoji = "😌",
                            IsActive = true,
                            MoodCategory = "Positive",
                            Name = "Calmo / Relaxado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7591)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7592),
                            Description = "Quando sente que fez algo legal",
                            Emoji = "😎",
                            IsActive = true,
                            MoodCategory = "Positive",
                            Name = "Orgulhoso",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7592)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7593),
                            Description = "Aprecia o que tem",
                            Emoji = "🙏",
                            IsActive = true,
                            MoodCategory = "Positive",
                            Name = "Grato / Satisfeito",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7594)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7595),
                            Description = "Desânimo ou sofrimento emocional",
                            Emoji = "😢",
                            IsActive = true,
                            MoodCategory = "Negative",
                            Name = "Triste / Melancólico",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7595)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7596),
                            Description = "Raiva ou impaciência",
                            Emoji = "😠",
                            IsActive = true,
                            MoodCategory = "Negative",
                            Name = "Irritado / Frustrado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7596)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7597),
                            Description = "Sensação de tensão ou medo",
                            Emoji = "😰",
                            IsActive = true,
                            MoodCategory = "Negative",
                            Name = "Ansioso / Preocupado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7598)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7599),
                            Description = "Pensamentos sobre erros",
                            Emoji = "😔",
                            IsActive = true,
                            MoodCategory = "Negative",
                            Name = "Culpado / Arrependido",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7599)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7600),
                            Description = "Falta de energia",
                            Emoji = "😴",
                            IsActive = true,
                            MoodCategory = "Negative",
                            Name = "Cansado / Desmotivado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7600)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7601),
                            Description = "Sem estímulo ou interesse",
                            Emoji = "😐",
                            IsActive = true,
                            MoodCategory = "Neutral",
                            Name = "Entediado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7601)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7602),
                            Description = "Não sabe bem o que pensar",
                            Emoji = "🤔",
                            IsActive = true,
                            MoodCategory = "Neutral",
                            Name = "Confuso / Indeciso",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7603)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7604),
                            Description = "Mente ativa, querendo descobrir",
                            Emoji = "🤨",
                            IsActive = true,
                            MoodCategory = "Neutral",
                            Name = "Curioso / Intrigado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 718, DateTimeKind.Utc).AddTicks(7604)
                        });
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId", "IsRead");

                    b.HasIndex("UserId", "SentAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.NotificationPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntensityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Normal");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("QuietEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("QuietStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NotificationType")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Token", "IsUsed", "ExpiresAt");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Relationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CelebrationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Annual");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("MetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetLocation")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RelationshipStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("User1Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("User2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipStartDate");

                    b.HasIndex("User2Id");

                    b.HasIndex("IsActive", "DeletedAt");

                    b.HasIndex("User1Id", "User2Id", "IsActive")
                        .IsUnique()
                        .HasFilter("IsActive = 1");

                    b.ToTable("Relationships", t =>
                        {
                            t.HasCheckConstraint("CK_Relationship_Users_Different", "User1Id != User2Id");
                        });
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.RelationshipInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId", "Status");

                    b.HasIndex("SenderId", "Status");

                    b.ToTable("RelationshipInvitations", t =>
                        {
                            t.HasCheckConstraint("CK_Invitation_Users_Different", "SenderId != ReceiverId");
                        });
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId");

                    b.HasIndex("IsActive", "ReminderDate");

                    b.HasIndex("UserId", "ReminderDate");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.SharedContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("access_count");

                    b.Property<long>("ContentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("content_id");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_accessed_at");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("relationship_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("RelationshipId", "ContentType", "ContentId");

                    b.HasIndex("Token", "IsRevoked", "ExpiresAt");

                    b.ToTable("shared_contents", (string)null);
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.StoryPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageBlob")
                        .HasColumnType("BLOB");

                    b.Property<DateOnly>("PageDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId", "PageDate");

                    b.HasIndex("RelationshipId", "PageNumber")
                        .IsUnique();

                    b.ToTable("StoryPages");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletionScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePhotoBlob")
                        .HasColumnType("BLOB");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#FF6B9D");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive", "DeletedAt");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.UserStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StatusUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatusUpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStatuses");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Wish", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageBlob")
                        .HasColumnType("BLOB");

                    b.Property<int>("ImportanceLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImportanceLevel");

                    b.HasIndex("Status");

                    b.HasIndex("RelationshipId", "DeletedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("RelationshipId", "Status", "DeletedAt");

                    b.ToTable("Wishes", t =>
                        {
                            t.HasCheckConstraint("CK_Wish_ImportanceLevel", "ImportanceLevel >= 1 AND ImportanceLevel <= 5");
                        });
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.WishCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WishCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(4455),
                            Description = "Lugares que o casal quer conhecer juntos",
                            Emoji = "🌍",
                            IsActive = true,
                            Name = "Viagem",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(4459)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5767),
                            Description = "Coisas que um quer ganhar ou comprar",
                            Emoji = "🎁",
                            IsActive = true,
                            Name = "Compras / Presentes",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5769)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5771),
                            Description = "Atividades e momentos a dois",
                            Emoji = "✨",
                            IsActive = true,
                            Name = "Experiências",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5771)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5772),
                            Description = "Objetivos compartilhados",
                            Emoji = "🎯",
                            IsActive = true,
                            Name = "Metas do Casal",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5773)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5774),
                            Description = "Ideias para o lar",
                            Emoji = "🏡",
                            IsActive = true,
                            Name = "Casa e Decoração",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5774)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5775),
                            Description = "Planos para aniversários e comemorações",
                            Emoji = "📅",
                            IsActive = true,
                            Name = "Datas Especiais",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5775)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5776),
                            Description = "Coisas individuais que melhoram o bem-estar",
                            Emoji = "🧘‍♀️",
                            IsActive = true,
                            Name = "Auto-cuidado",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5776)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5777),
                            Description = "Desejos relacionados a pets",
                            Emoji = "🐾",
                            IsActive = true,
                            Name = "Animais de Estimação",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5778)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5779),
                            Description = "Sonhos artísticos ou hobbies",
                            Emoji = "🎨",
                            IsActive = true,
                            Name = "Projetos Criativos",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5779)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5780),
                            Description = "Lugares para comer e receitas",
                            Emoji = "🍝",
                            IsActive = true,
                            Name = "Gastronomia",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5780)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5781),
                            Description = "Coisas mais distantes ou inspiracionais",
                            Emoji = "🌠",
                            IsActive = true,
                            Name = "Sonhos Grandes",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5781)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5782),
                            Description = "Desejos voltados a ajudar outros",
                            Emoji = "💗",
                            IsActive = true,
                            Name = "Doações e Impacto",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 24, 22, 717, DateTimeKind.Utc).AddTicks(5783)
                        });
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.WishComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WishId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WishId", "CreatedAt");

                    b.ToTable("WishComments");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.DailyActivity", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("DailyActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Favorite", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.InitialSetup", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("InitialSetups")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("InitialSetups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Memory", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("Memories")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MemoryMedia", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Memory", "Memory")
                        .WithMany("Media")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MemoryTag", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Memory", "Memory")
                        .WithMany("Tags")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MessageMedia", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.ChatMessage", "ChatMessage")
                        .WithMany("Media")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MoodLog", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.MoodType", "MoodType")
                        .WithMany("MoodLogs")
                        .HasForeignKey("MoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("MoodLogs")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("MoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodType");

                    b.Navigation("Relationship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Notification", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("Notifications")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.NotificationPreference", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("NotificationPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Relationship", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User1")
                        .WithMany("RelationshipsAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User2")
                        .WithMany("RelationshipsAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.RelationshipInvitation", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "Receiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "Sender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Reminder", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany()
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.SharedContent", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany()
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.StoryPage", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("StoryPages")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.UserStatus", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithOne("UserStatus")
                        .HasForeignKey("Heloilo.Domain.Models.Entities.UserStatus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Wish", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.WishCategory", "Category")
                        .WithMany("Wishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Heloilo.Domain.Models.Entities.Relationship", "Relationship")
                        .WithMany("Wishes")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("Wishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Relationship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.WishComment", b =>
                {
                    b.HasOne("Heloilo.Domain.Models.Entities.User", "User")
                        .WithMany("WishComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heloilo.Domain.Models.Entities.Wish", "Wish")
                        .WithMany("Comments")
                        .HasForeignKey("WishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Wish");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.ChatMessage", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Memory", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.MoodType", b =>
                {
                    b.Navigation("MoodLogs");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Relationship", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("InitialSetups");

                    b.Navigation("Memories");

                    b.Navigation("MoodLogs");

                    b.Navigation("Notifications");

                    b.Navigation("StoryPages");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.User", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("InitialSetups");

                    b.Navigation("MoodLogs");

                    b.Navigation("NotificationPreferences");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("RelationshipsAsUser1");

                    b.Navigation("RelationshipsAsUser2");

                    b.Navigation("SentInvitations");

                    b.Navigation("SentMessages");

                    b.Navigation("UserStatus");

                    b.Navigation("WishComments");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.Wish", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Heloilo.Domain.Models.Entities.WishCategory", b =>
                {
                    b.Navigation("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
